version: "3.9"

services:
  api:
    build: .
    container_name: dinogems-api
    command: node src/server.js
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./src/buffer/pending:/app/src/buffer/pending

  worker:
    build: .
    container_name: dinogems-worker
    command: node src/services/buffer.worker.js
    env_file:
      - .env
    restart: always
    volumes:
      - ./src/buffer/pending:/app/src/buffer/pending
